### ISSUE TITLE
规则会误伤Apple Music

### ISSUE THREAD

**Issue by betacat-ha** [Crazy-Z7/AdGuard#1]
您好！非常感谢您的工作，在使用过程中发现了如下问题：\*music\* 这条规则会使*.music.apple.com也进入Mitm，令Apple Music无法正常工作。据了解，Apple的部分服务会拒绝Mitm。
![12EBF218-3C2E-4FD6-BE10-48A6F2B4D910](https://user-images.githubusercontent.com/36399070/209742332-abb0538e-6797-4fac-8282-6998dd08ff7f.jpeg)

**Comment by Crazy-Z7** [comment]
最新规则已修复，更新即可

**Comment by betacat-ha** [comment]
已确认修复，再次感谢您！
